/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = qan.Client.OpenAPIDateConverter;

namespace qan.qan
{
    /// <summary>
    /// OutputChainId
    /// </summary>
    [DataContract(Name = "Output_chainId")]
    public partial class OutputChainId : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OutputChainId" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OutputChainId() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OutputChainId" /> class.
        /// </summary>
        /// <param name="chainId">A decimal value in string format which represents an integer of the chain ID (required).</param>
        public OutputChainId(string chainId = default(string))
        {
            // to ensure "chainId" is required (not null)
            if (chainId == null)
            {
                throw new ArgumentNullException("chainId is a required property for OutputChainId and cannot be null");
            }
            this.ChainId = chainId;
        }

        /// <summary>
        /// A URL to the JSON Schema for this object.
        /// </summary>
        /// <value>A URL to the JSON Schema for this object.</value>
        [DataMember(Name = "$schema", EmitDefaultValue = false)]
        public string Schema { get; private set; }

        /// <summary>
        /// Returns false as Schema should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSchema()
        {
            return false;
        }
        /// <summary>
        /// A decimal value in string format which represents an integer of the chain ID
        /// </summary>
        /// <value>A decimal value in string format which represents an integer of the chain ID</value>
        [DataMember(Name = "ChainId", IsRequired = true, EmitDefaultValue = true)]
        public string ChainId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OutputChainId {\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("  ChainId: ").Append(ChainId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
