/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = qan.Client.OpenAPIDateConverter;

namespace qan.qan
{
    /// <summary>
    /// OutputGetBlockReceipts
    /// </summary>
    [DataContract(Name = "Output_getBlockReceipts")]
    public partial class OutputGetBlockReceipts : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OutputGetBlockReceipts" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OutputGetBlockReceipts() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OutputGetBlockReceipts" /> class.
        /// </summary>
        /// <param name="transactionReceipts">An array of transaction receipt objects (required).</param>
        public OutputGetBlockReceipts(List<ResponseTransactionReceipt> transactionReceipts = default(List<ResponseTransactionReceipt>))
        {
            // to ensure "transactionReceipts" is required (not null)
            if (transactionReceipts == null)
            {
                throw new ArgumentNullException("transactionReceipts is a required property for OutputGetBlockReceipts and cannot be null");
            }
            this.TransactionReceipts = transactionReceipts;
        }

        /// <summary>
        /// A URL to the JSON Schema for this object.
        /// </summary>
        /// <value>A URL to the JSON Schema for this object.</value>
        [DataMember(Name = "$schema", EmitDefaultValue = false)]
        public string Schema { get; private set; }

        /// <summary>
        /// Returns false as Schema should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSchema()
        {
            return false;
        }
        /// <summary>
        /// An array of transaction receipt objects
        /// </summary>
        /// <value>An array of transaction receipt objects</value>
        [DataMember(Name = "TransactionReceipts", IsRequired = true, EmitDefaultValue = true)]
        public List<ResponseTransactionReceipt> TransactionReceipts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OutputGetBlockReceipts {\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("  TransactionReceipts: ").Append(TransactionReceipts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
