/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = qan.Client.OpenAPIDateConverter;

namespace qan.qan
{
    /// <summary>
    /// ResponseStorageEntry
    /// </summary>
    [DataContract(Name = "Response_StorageEntry")]
    public partial class ResponseStorageEntry : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseStorageEntry" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ResponseStorageEntry() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseStorageEntry" /> class.
        /// </summary>
        /// <param name="key">The requested storage key (required).</param>
        /// <param name="proof">An array of rlp-serialized MerkleTree-Nodes which starts with the stateRoot-Node and follows the path of the SHA3 address as key (required).</param>
        /// <param name="value">The storage value (required).</param>
        public ResponseStorageEntry(string key = default(string), string proof = default(string), string value = default(string))
        {
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for ResponseStorageEntry and cannot be null");
            }
            this.Key = key;
            // to ensure "proof" is required (not null)
            if (proof == null)
            {
                throw new ArgumentNullException("proof is a required property for ResponseStorageEntry and cannot be null");
            }
            this.Proof = proof;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for ResponseStorageEntry and cannot be null");
            }
            this.Value = value;
        }

        /// <summary>
        /// The requested storage key
        /// </summary>
        /// <value>The requested storage key</value>
        [DataMember(Name = "Key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// An array of rlp-serialized MerkleTree-Nodes which starts with the stateRoot-Node and follows the path of the SHA3 address as key
        /// </summary>
        /// <value>An array of rlp-serialized MerkleTree-Nodes which starts with the stateRoot-Node and follows the path of the SHA3 address as key</value>
        [DataMember(Name = "Proof", IsRequired = true, EmitDefaultValue = true)]
        public string Proof { get; set; }

        /// <summary>
        /// The storage value
        /// </summary>
        /// <value>The storage value</value>
        [DataMember(Name = "Value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResponseStorageEntry {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Proof: ").Append(Proof).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
