/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing EstimateGasObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EstimateGasObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EstimateGasObject
        //private EstimateGasObject instance;

        public EstimateGasObjectTests()
        {
            // TODO uncomment below to create an instance of EstimateGasObject
            //instance = new EstimateGasObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EstimateGasObject
        /// </summary>
        [Fact]
        public void EstimateGasObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" EstimateGasObject
            //Assert.IsType<EstimateGasObject>(instance);
        }

        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Fact]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'StateDiff'
        /// </summary>
        [Fact]
        public void StateDiffTest()
        {
            // TODO unit test for the property 'StateDiff'
        }
    }
}
