/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing InputFeeHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InputFeeHistoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InputFeeHistory
        //private InputFeeHistory instance;

        public InputFeeHistoryTests()
        {
            // TODO uncomment below to create an instance of InputFeeHistory
            //instance = new InputFeeHistory();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InputFeeHistory
        /// </summary>
        [Fact]
        public void InputFeeHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsType" InputFeeHistory
            //Assert.IsType<InputFeeHistory>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'BlockCount'
        /// </summary>
        [Fact]
        public void BlockCountTest()
        {
            // TODO unit test for the property 'BlockCount'
        }

        /// <summary>
        /// Test the property 'NewestBlock'
        /// </summary>
        [Fact]
        public void NewestBlockTest()
        {
            // TODO unit test for the property 'NewestBlock'
        }

        /// <summary>
        /// Test the property 'RewardPercentiles'
        /// </summary>
        [Fact]
        public void RewardPercentilesTest()
        {
            // TODO unit test for the property 'RewardPercentiles'
        }
    }
}
