/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing InputGetLogs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InputGetLogsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InputGetLogs
        //private InputGetLogs instance;

        public InputGetLogsTests()
        {
            // TODO uncomment below to create an instance of InputGetLogs
            //instance = new InputGetLogs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InputGetLogs
        /// </summary>
        [Fact]
        public void InputGetLogsInstanceTest()
        {
            // TODO uncomment below to test "IsType" InputGetLogs
            //Assert.IsType<InputGetLogs>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'BlockHash'
        /// </summary>
        [Fact]
        public void BlockHashTest()
        {
            // TODO unit test for the property 'BlockHash'
        }

        /// <summary>
        /// Test the property 'FromBlock'
        /// </summary>
        [Fact]
        public void FromBlockTest()
        {
            // TODO unit test for the property 'FromBlock'
        }

        /// <summary>
        /// Test the property 'ToBlock'
        /// </summary>
        [Fact]
        public void ToBlockTest()
        {
            // TODO unit test for the property 'ToBlock'
        }

        /// <summary>
        /// Test the property 'Topics'
        /// </summary>
        [Fact]
        public void TopicsTest()
        {
            // TODO unit test for the property 'Topics'
        }
    }
}
