/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing OutputChainId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputChainIdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputChainId
        //private OutputChainId instance;

        public OutputChainIdTests()
        {
            // TODO uncomment below to create an instance of OutputChainId
            //instance = new OutputChainId();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputChainId
        /// </summary>
        [Fact]
        public void OutputChainIdInstanceTest()
        {
            // TODO uncomment below to test "IsType" OutputChainId
            //Assert.IsType<OutputChainId>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'ChainId'
        /// </summary>
        [Fact]
        public void ChainIdTest()
        {
            // TODO unit test for the property 'ChainId'
        }
    }
}
