/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing OutputNewFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputNewFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputNewFilter
        //private OutputNewFilter instance;

        public OutputNewFilterTests()
        {
            // TODO uncomment below to create an instance of OutputNewFilter
            //instance = new OutputNewFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputNewFilter
        /// </summary>
        [Fact]
        public void OutputNewFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" OutputNewFilter
            //Assert.IsType<OutputNewFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'FilterId'
        /// </summary>
        [Fact]
        public void FilterIdTest()
        {
            // TODO unit test for the property 'FilterId'
        }
    }
}
