/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing OutputGetProof
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputGetProofTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputGetProof
        //private OutputGetProof instance;

        public OutputGetProofTests()
        {
            // TODO uncomment below to create an instance of OutputGetProof
            //instance = new OutputGetProof();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputGetProof
        /// </summary>
        [Fact]
        public void OutputGetProofInstanceTest()
        {
            // TODO uncomment below to test "IsType" OutputGetProof
            //Assert.IsType<OutputGetProof>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'AccountProof'
        /// </summary>
        [Fact]
        public void AccountProofTest()
        {
            // TODO unit test for the property 'AccountProof'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }

        /// <summary>
        /// Test the property 'CodeHash'
        /// </summary>
        [Fact]
        public void CodeHashTest()
        {
            // TODO unit test for the property 'CodeHash'
        }

        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Fact]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }

        /// <summary>
        /// Test the property 'StorageHash'
        /// </summary>
        [Fact]
        public void StorageHashTest()
        {
            // TODO unit test for the property 'StorageHash'
        }

        /// <summary>
        /// Test the property 'StorageProof'
        /// </summary>
        [Fact]
        public void StorageProofTest()
        {
            // TODO unit test for the property 'StorageProof'
        }
    }
}
