/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing OutputGetLogs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputGetLogsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputGetLogs
        //private OutputGetLogs instance;

        public OutputGetLogsTests()
        {
            // TODO uncomment below to create an instance of OutputGetLogs
            //instance = new OutputGetLogs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputGetLogs
        /// </summary>
        [Fact]
        public void OutputGetLogsInstanceTest()
        {
            // TODO uncomment below to test "IsType" OutputGetLogs
            //Assert.IsType<OutputGetLogs>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Logs'
        /// </summary>
        [Fact]
        public void LogsTest()
        {
            // TODO unit test for the property 'Logs'
        }
    }
}
