/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing OutputXlinkValid
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputXlinkValidTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputXlinkValid
        //private OutputXlinkValid instance;

        public OutputXlinkValidTests()
        {
            // TODO uncomment below to create an instance of OutputXlinkValid
            //instance = new OutputXlinkValid();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputXlinkValid
        /// </summary>
        [Fact]
        public void OutputXlinkValidInstanceTest()
        {
            // TODO uncomment below to test "IsType" OutputXlinkValid
            //Assert.IsType<OutputXlinkValid>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Validity'
        /// </summary>
        [Fact]
        public void ValidityTest()
        {
            // TODO unit test for the property 'Validity'
        }
    }
}
