/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing OutputFeeHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputFeeHistoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputFeeHistory
        //private OutputFeeHistory instance;

        public OutputFeeHistoryTests()
        {
            // TODO uncomment below to create an instance of OutputFeeHistory
            //instance = new OutputFeeHistory();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputFeeHistory
        /// </summary>
        [Fact]
        public void OutputFeeHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsType" OutputFeeHistory
            //Assert.IsType<OutputFeeHistory>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'BaseFeePerGas'
        /// </summary>
        [Fact]
        public void BaseFeePerGasTest()
        {
            // TODO unit test for the property 'BaseFeePerGas'
        }

        /// <summary>
        /// Test the property 'GasUsedRatio'
        /// </summary>
        [Fact]
        public void GasUsedRatioTest()
        {
            // TODO unit test for the property 'GasUsedRatio'
        }

        /// <summary>
        /// Test the property 'OldestBlock'
        /// </summary>
        [Fact]
        public void OldestBlockTest()
        {
            // TODO unit test for the property 'OldestBlock'
        }

        /// <summary>
        /// Test the property 'Reward'
        /// </summary>
        [Fact]
        public void RewardTest()
        {
            // TODO unit test for the property 'Reward'
        }
    }
}
