/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseWithdrawals
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseWithdrawalsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseWithdrawals
        //private ResponseWithdrawals instance;

        public ResponseWithdrawalsTests()
        {
            // TODO uncomment below to create an instance of ResponseWithdrawals
            //instance = new ResponseWithdrawals();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseWithdrawals
        /// </summary>
        [Fact]
        public void ResponseWithdrawalsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseWithdrawals
            //Assert.IsType<ResponseWithdrawals>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'ValidatorIndex'
        /// </summary>
        [Fact]
        public void ValidatorIndexTest()
        {
            // TODO unit test for the property 'ValidatorIndex'
        }
    }
}
