/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseTransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseTransaction
        //private ResponseTransaction instance;

        public ResponseTransactionTests()
        {
            // TODO uncomment below to create an instance of ResponseTransaction
            //instance = new ResponseTransaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseTransaction
        /// </summary>
        [Fact]
        public void ResponseTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseTransaction
            //Assert.IsType<ResponseTransaction>(instance);
        }

        /// <summary>
        /// Test the property 'AccessList'
        /// </summary>
        [Fact]
        public void AccessListTest()
        {
            // TODO unit test for the property 'AccessList'
        }

        /// <summary>
        /// Test the property 'BlockHash'
        /// </summary>
        [Fact]
        public void BlockHashTest()
        {
            // TODO unit test for the property 'BlockHash'
        }

        /// <summary>
        /// Test the property 'BlockNumber'
        /// </summary>
        [Fact]
        public void BlockNumberTest()
        {
            // TODO unit test for the property 'BlockNumber'
        }

        /// <summary>
        /// Test the property 'ChainId'
        /// </summary>
        [Fact]
        public void ChainIdTest()
        {
            // TODO unit test for the property 'ChainId'
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'Gas'
        /// </summary>
        [Fact]
        public void GasTest()
        {
            // TODO unit test for the property 'Gas'
        }

        /// <summary>
        /// Test the property 'GasPrice'
        /// </summary>
        [Fact]
        public void GasPriceTest()
        {
            // TODO unit test for the property 'GasPrice'
        }

        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }

        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Fact]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }

        /// <summary>
        /// Test the property 'MaxFeePerGas'
        /// </summary>
        [Fact]
        public void MaxFeePerGasTest()
        {
            // TODO unit test for the property 'MaxFeePerGas'
        }

        /// <summary>
        /// Test the property 'MaxPriorityFeePerGas'
        /// </summary>
        [Fact]
        public void MaxPriorityFeePerGasTest()
        {
            // TODO unit test for the property 'MaxPriorityFeePerGas'
        }

        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Fact]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }

        /// <summary>
        /// Test the property 'R'
        /// </summary>
        [Fact]
        public void RTest()
        {
            // TODO unit test for the property 'R'
        }

        /// <summary>
        /// Test the property 'S'
        /// </summary>
        [Fact]
        public void STest()
        {
            // TODO unit test for the property 'S'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'TransactionIndex'
        /// </summary>
        [Fact]
        public void TransactionIndexTest()
        {
            // TODO unit test for the property 'TransactionIndex'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'V'
        /// </summary>
        [Fact]
        public void VTest()
        {
            // TODO unit test for the property 'V'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
