/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseTransactionReceipt
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseTransactionReceiptTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseTransactionReceipt
        //private ResponseTransactionReceipt instance;

        public ResponseTransactionReceiptTests()
        {
            // TODO uncomment below to create an instance of ResponseTransactionReceipt
            //instance = new ResponseTransactionReceipt();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseTransactionReceipt
        /// </summary>
        [Fact]
        public void ResponseTransactionReceiptInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseTransactionReceipt
            //Assert.IsType<ResponseTransactionReceipt>(instance);
        }

        /// <summary>
        /// Test the property 'BlockHash'
        /// </summary>
        [Fact]
        public void BlockHashTest()
        {
            // TODO unit test for the property 'BlockHash'
        }

        /// <summary>
        /// Test the property 'BlockNumber'
        /// </summary>
        [Fact]
        public void BlockNumberTest()
        {
            // TODO unit test for the property 'BlockNumber'
        }

        /// <summary>
        /// Test the property 'ContractAddress'
        /// </summary>
        [Fact]
        public void ContractAddressTest()
        {
            // TODO unit test for the property 'ContractAddress'
        }

        /// <summary>
        /// Test the property 'CumulativeGasUsed'
        /// </summary>
        [Fact]
        public void CumulativeGasUsedTest()
        {
            // TODO unit test for the property 'CumulativeGasUsed'
        }

        /// <summary>
        /// Test the property 'EffectiveGasPrice'
        /// </summary>
        [Fact]
        public void EffectiveGasPriceTest()
        {
            // TODO unit test for the property 'EffectiveGasPrice'
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'GasUsed'
        /// </summary>
        [Fact]
        public void GasUsedTest()
        {
            // TODO unit test for the property 'GasUsed'
        }

        /// <summary>
        /// Test the property 'Logs'
        /// </summary>
        [Fact]
        public void LogsTest()
        {
            // TODO unit test for the property 'Logs'
        }

        /// <summary>
        /// Test the property 'LogsBloom'
        /// </summary>
        [Fact]
        public void LogsBloomTest()
        {
            // TODO unit test for the property 'LogsBloom'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'TransactionHash'
        /// </summary>
        [Fact]
        public void TransactionHashTest()
        {
            // TODO unit test for the property 'TransactionHash'
        }

        /// <summary>
        /// Test the property 'TransactionIndex'
        /// </summary>
        [Fact]
        public void TransactionIndexTest()
        {
            // TODO unit test for the property 'TransactionIndex'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
