/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseLog
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseLogTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseLog
        //private ResponseLog instance;

        public ResponseLogTests()
        {
            // TODO uncomment below to create an instance of ResponseLog
            //instance = new ResponseLog();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseLog
        /// </summary>
        [Fact]
        public void ResponseLogInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseLog
            //Assert.IsType<ResponseLog>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'BlockHash'
        /// </summary>
        [Fact]
        public void BlockHashTest()
        {
            // TODO unit test for the property 'BlockHash'
        }

        /// <summary>
        /// Test the property 'BlockNumber'
        /// </summary>
        [Fact]
        public void BlockNumberTest()
        {
            // TODO unit test for the property 'BlockNumber'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'LogIndex'
        /// </summary>
        [Fact]
        public void LogIndexTest()
        {
            // TODO unit test for the property 'LogIndex'
        }

        /// <summary>
        /// Test the property 'Removed'
        /// </summary>
        [Fact]
        public void RemovedTest()
        {
            // TODO unit test for the property 'Removed'
        }

        /// <summary>
        /// Test the property 'Topics'
        /// </summary>
        [Fact]
        public void TopicsTest()
        {
            // TODO unit test for the property 'Topics'
        }

        /// <summary>
        /// Test the property 'TransactionHash'
        /// </summary>
        [Fact]
        public void TransactionHashTest()
        {
            // TODO unit test for the property 'TransactionHash'
        }

        /// <summary>
        /// Test the property 'TransactionIndex'
        /// </summary>
        [Fact]
        public void TransactionIndexTest()
        {
            // TODO unit test for the property 'TransactionIndex'
        }
    }
}
