/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseBlock
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseBlockTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseBlock
        //private ResponseBlock instance;

        public ResponseBlockTests()
        {
            // TODO uncomment below to create an instance of ResponseBlock
            //instance = new ResponseBlock();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseBlock
        /// </summary>
        [Fact]
        public void ResponseBlockInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseBlock
            //Assert.IsType<ResponseBlock>(instance);
        }

        /// <summary>
        /// Test the property 'BaseFeePerGas'
        /// </summary>
        [Fact]
        public void BaseFeePerGasTest()
        {
            // TODO unit test for the property 'BaseFeePerGas'
        }

        /// <summary>
        /// Test the property 'Difficulty'
        /// </summary>
        [Fact]
        public void DifficultyTest()
        {
            // TODO unit test for the property 'Difficulty'
        }

        /// <summary>
        /// Test the property 'ExtraData'
        /// </summary>
        [Fact]
        public void ExtraDataTest()
        {
            // TODO unit test for the property 'ExtraData'
        }

        /// <summary>
        /// Test the property 'GasLimit'
        /// </summary>
        [Fact]
        public void GasLimitTest()
        {
            // TODO unit test for the property 'GasLimit'
        }

        /// <summary>
        /// Test the property 'GasUsed'
        /// </summary>
        [Fact]
        public void GasUsedTest()
        {
            // TODO unit test for the property 'GasUsed'
        }

        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }

        /// <summary>
        /// Test the property 'LogsBloom'
        /// </summary>
        [Fact]
        public void LogsBloomTest()
        {
            // TODO unit test for the property 'LogsBloom'
        }

        /// <summary>
        /// Test the property 'Miner'
        /// </summary>
        [Fact]
        public void MinerTest()
        {
            // TODO unit test for the property 'Miner'
        }

        /// <summary>
        /// Test the property 'MixHash'
        /// </summary>
        [Fact]
        public void MixHashTest()
        {
            // TODO unit test for the property 'MixHash'
        }

        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Fact]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }

        /// <summary>
        /// Test the property 'ParentHash'
        /// </summary>
        [Fact]
        public void ParentHashTest()
        {
            // TODO unit test for the property 'ParentHash'
        }

        /// <summary>
        /// Test the property 'ReceiptsRoot'
        /// </summary>
        [Fact]
        public void ReceiptsRootTest()
        {
            // TODO unit test for the property 'ReceiptsRoot'
        }

        /// <summary>
        /// Test the property 'Sha3Uncles'
        /// </summary>
        [Fact]
        public void Sha3UnclesTest()
        {
            // TODO unit test for the property 'Sha3Uncles'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'StateRoot'
        /// </summary>
        [Fact]
        public void StateRootTest()
        {
            // TODO unit test for the property 'StateRoot'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'TotalDifficulty'
        /// </summary>
        [Fact]
        public void TotalDifficultyTest()
        {
            // TODO unit test for the property 'TotalDifficulty'
        }

        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Fact]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }

        /// <summary>
        /// Test the property 'TransactionsRoot'
        /// </summary>
        [Fact]
        public void TransactionsRootTest()
        {
            // TODO unit test for the property 'TransactionsRoot'
        }

        /// <summary>
        /// Test the property 'Uncles'
        /// </summary>
        [Fact]
        public void UnclesTest()
        {
            // TODO unit test for the property 'Uncles'
        }

        /// <summary>
        /// Test the property 'Withdrawals'
        /// </summary>
        [Fact]
        public void WithdrawalsTest()
        {
            // TODO unit test for the property 'Withdrawals'
        }

        /// <summary>
        /// Test the property 'WithdrawalsRoot'
        /// </summary>
        [Fact]
        public void WithdrawalsRootTest()
        {
            // TODO unit test for the property 'WithdrawalsRoot'
        }
    }
}
