/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseStorageEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseStorageEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseStorageEntry
        //private ResponseStorageEntry instance;

        public ResponseStorageEntryTests()
        {
            // TODO uncomment below to create an instance of ResponseStorageEntry
            //instance = new ResponseStorageEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseStorageEntry
        /// </summary>
        [Fact]
        public void ResponseStorageEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseStorageEntry
            //Assert.IsType<ResponseStorageEntry>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Proof'
        /// </summary>
        [Fact]
        public void ProofTest()
        {
            // TODO unit test for the property 'Proof'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
