/*
 * QAN AutoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using qan.qan;
using qan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace qan.Test.Model
{
    /// <summary>
    ///  Class for testing SyncStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SyncStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SyncStatus
        //private SyncStatus instance;

        public SyncStatusTests()
        {
            // TODO uncomment below to create an instance of SyncStatus
            //instance = new SyncStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SyncStatus
        /// </summary>
        [Fact]
        public void SyncStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" SyncStatus
            //Assert.IsType<SyncStatus>(instance);
        }

        /// <summary>
        /// Test the property 'CurrentBlock'
        /// </summary>
        [Fact]
        public void CurrentBlockTest()
        {
            // TODO unit test for the property 'CurrentBlock'
        }

        /// <summary>
        /// Test the property 'HighestBlock'
        /// </summary>
        [Fact]
        public void HighestBlockTest()
        {
            // TODO unit test for the property 'HighestBlock'
        }

        /// <summary>
        /// Test the property 'StartingBlock'
        /// </summary>
        [Fact]
        public void StartingBlockTest()
        {
            // TODO unit test for the property 'StartingBlock'
        }
    }
}
